map $request_uri $loggable {
  /nginx-check 0;
  default 1;
}

server {
  listen       80;
  listen  [::]:80;
  server_name  localhost;

  location / {
    access_log /var/log/nginx/access.log  main if=$loggable;
    root   /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }

  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}
